title: DeveloperOC.com
description: "Satellite - jekyll blog theme"
logo_img: "/assets/img/favicon.ico"
profile_img: "/assets/img/profile.webp"

# Social Links
email: "oortcloud98@gmail.com"
github_username: cloud1202
notion: 2a85819b9aa780a29229dac0038335df
twitter_username: twitter
instagram_username: instagram
linkedin_username: linkedin
facebook_username: facebook

# External API
giscus_repo: "cloud1202/cloud1202.github.io"
giscus_repoId: "R_kgDOHxWNpQ"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOHxWNpc4Cx4YL"
goatcounter_code: cloud1202
google_analytics: G-0JYDGDVPBB

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl: /cloud1202.github.io

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
